name: Build and publish Docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip-build')"
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
        
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/tutu-inc/rocket
          tag-custom: latest
          tag-sha: true
          tag-semver: |
            {{raw}}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PACKAGE_TOKEN }}
  
      - name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          # platform: linux/amd64, linux/arm64
          file: ./Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}