name: Build and publish Docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip-build')"
    runs-on: ubuntu-latest
    
    steps:   
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: ghcr.io/tutu-inc/rocket
          tag-sha: true
          tag-edge: false
          tag-latest: true
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PACKAGE_TOKEN }}
          
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          tags: ${{ steps.docker_meta.outputs.tags }} 
          #file: ./Dockerfile
          
      - name: Push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          #file: ./Dockerfile

        